name: ecommerce backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t nikhilmhatre0317/ecommerce-backend .
      - name: Publish image to docker hub
        run: docker push nikhilmhatre0317/ecommerce-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull nikhilmhatre0317/ecommerce-backend:latest
      - name: Delete old container
        run: docker rm -f ecommerce-backend-container
      - name: Run docker container
        run: docker run -d -p 80:80 --name ecommerce-backend-container nikhilmhatre0317/ecommerce-backend
